import { Task } from '@/types';

export const TASKS: Task[] = [
  // ===== 1-100 : TÂCHES PRINCIPALES =====
  { id: 1, name: "Essuyer plans de travail", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 5 },
  { id: 2, name: "Nettoyer évier", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 5 },
  { id: 3, name: "Balayer/laver sol cuisine", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 10 },
  { id: 4, name: "Faire vaisselle", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 15 },
  { id: 5, name: "Vider poubelle", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 3 },
  { id: 6, name: "Dépoussiérer surfaces visibles", frequency: "quotidienne", zone: "Salon", estimatedTime: 8 },
  { id: 7, name: "Aspirer/laver sol salon", frequency: "quotidienne", zone: "Salon", estimatedTime: 12 },
  { id: 8, name: "Ranger objets/coussins", frequency: "quotidienne", zone: "Salon", estimatedTime: 5 },
  { id: 9, name: "Nettoyer écrans TV/ordinateur", frequency: "quotidienne", zone: "Salon", estimatedTime: 5 },
  { id: 10, name: "Nettoyer lavabo", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 5 },
  { id: 11, name: "Désinfecter toilettes", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 8 },
  { id: 12, name: "Essuyer miroirs", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 3 },
  { id: 13, name: "Remplacer serviettes", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 3 },
  { id: 14, name: "Faire le lit", frequency: "quotidienne", zone: "Chambres", estimatedTime: 5 },
  { id: 15, name: "Ranger vêtements/objets", frequency: "quotidienne", zone: "Chambres", estimatedTime: 10 },
  { id: 16, name: "Aérer pièce", frequency: "quotidienne", zone: "Chambres", estimatedTime: 2 },
  { id: 17, name: "Aspirer sol chambres", frequency: "quotidienne", zone: "Chambres", estimatedTime: 10 },
  { id: 18, name: "Nettoyer micro-ondes intérieur", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 10 },
  { id: 19, name: "Nettoyer four", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 20 },
  { id: 20, name: "Dégraisser portes placard", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 15 },
  { id: 21, name: "Désinfecter frigo (tri périmés)", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 15 },
  { id: 22, name: "Dépoussiérer meubles/objets", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 20 },
  { id: 23, name: "Nettoyer fenêtres", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 25 },
  { id: 24, name: "Aspirer tapis/canapés", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 15 },
  { id: 25, name: "Nettoyer carreaux/joints", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 20 },
  { id: 26, name: "Désinfecter robinets/pommeau", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 27, name: "Nettoyer brosses/accessoires", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 28, name: "Changer draps/taies", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 15 },
  { id: 29, name: "Nettoyer sous lit/meubles", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 20 },
  { id: 30, name: "Ranger armoire/trier vêtements", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 30 },
  { id: 31, name: "Nettoyer hotte/grilles aération", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 25 },
  { id: 32, name: "Laver intérieur placards", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 40 },
  { id: 33, name: "Détartrer cafetière/bouilloire", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 15 },
  { id: 34, name: "Laver rideaux/textiles", frequency: "mensuelle", zone: "Salon", estimatedTime: 30 },
  { id: 35, name: "Polir meubles bois", frequency: "mensuelle", zone: "Salon", estimatedTime: 25 },
  { id: 36, name: "Dépoussiérer luminaires", frequency: "mensuelle", zone: "Salon", estimatedTime: 20 },
  { id: 37, name: "Détartrer robinets/douche", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 20 },
  { id: 38, name: "Nettoyer évacuations eau", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 15 },
  { id: 39, name: "Laver tapis bain", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 10 },
  { id: 40, name: "Nettoyer matelas (aspiration)", frequency: "mensuelle", zone: "Chambres", estimatedTime: 20 },
  { id: 41, name: "Réorganiser tiroirs/étagères", frequency: "mensuelle", zone: "Chambres", estimatedTime: 35 },
  { id: 42, name: "Laver oreillers/couettes", frequency: "mensuelle", zone: "Chambres", estimatedTime: 30 },
  { id: 43, name: "Pyrolyser four", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 45 },
  { id: 44, name: "Nettoyer lave-vaisselle (vinaigre)", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 20 },
  { id: 45, name: "Nettoyer sous frigo/four", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 40 },
  { id: 46, name: "Récurer évier", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 15 },
  { id: 47, name: "Nettoyer portes placard int/ext", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 35 },
  { id: 48, name: "Désinfecter poubelle/compost", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 15 },
  { id: 49, name: "Lessiver murs/interrupteurs", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 45 },
  { id: 50, name: "Laver housses coussins/canapé", frequency: "saisonnière", zone: "Salon", estimatedTime: 30 },
  { id: 51, name: "Nettoyer tapis vapeur", frequency: "saisonnière", zone: "Salon", estimatedTime: 40 },
  { id: 52, name: "Épousseter moulures hauteur", frequency: "saisonnière", zone: "Salon", estimatedTime: 25 },
  { id: 53, name: "Nettoyer cadres/étagères/livres", frequency: "saisonnière", zone: "Salon", estimatedTime: 30 },
  { id: 54, name: "Lessiver murs/interrupteurs", frequency: "saisonnière", zone: "Salon", estimatedTime: 45 },
  { id: 55, name: "Laver intérieurs placards", frequency: "saisonnière", zone: "Salon", estimatedTime: 35 },
  { id: 56, name: "Nettoyer plinthes chauffage", frequency: "saisonnière", zone: "Salon", estimatedTime: 20 },
  { id: 57, name: "Laver rideaux/stores", frequency: "saisonnière", zone: "Chambres", estimatedTime: 30 },
  { id: 58, name: "Laver alaises/draps/housses", frequency: "saisonnière", zone: "Chambres", estimatedTime: 25 },
  { id: 59, name: "Épousseter tapis", frequency: "saisonnière", zone: "Chambres", estimatedTime: 15 },
  { id: 60, name: "Tourner matelas", frequency: "saisonnière", zone: "Chambres", estimatedTime: 10 },
  { id: 61, name: "Vider/laver étagères placards", frequency: "saisonnière", zone: "Chambres", estimatedTime: 40 },
  { id: 62, name: "Nettoyer jouets enfants", frequency: "saisonnière", zone: "Chambres", estimatedTime: 25 },
  { id: 63, name: "Nettoyer cuvette toilettes", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 15 },
  { id: 64, name: "Nettoyer portes/placards", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 20 },
  { id: 65, name: "Nettoyer vitre/rideau douche", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 20 },
  { id: 66, name: "Nettoyer machine laver (vinaigre)", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 20 },
  { id: 67, name: "Enlever cheveux lavabo", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 10 },
  { id: 68, name: "Nettoyer ventilateur plafond", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 15 },
  { id: 69, name: "Trier produits périmés", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 15 },
  { id: 70, name: "Nettoyer clavier/écran ordi", frequency: "saisonnière", zone: "Bureau", estimatedTime: 15 },
  { id: 71, name: "Classer/trier papiers", frequency: "saisonnière", zone: "Bureau", estimatedTime: 45 },
  { id: 72, name: "Laver tapis entrée", frequency: "saisonnière", zone: "Entrée", estimatedTime: 20 },
  { id: 73, name: "Trier chaussures", frequency: "saisonnière", zone: "Entrée", estimatedTime: 25 },
  { id: 74, name: "Ranger manteaux/sacs", frequency: "saisonnière", zone: "Entrée", estimatedTime: 20 },
  { id: 75, name: "Lessiver murs entrée", frequency: "annuelle", zone: "Entrée", estimatedTime: 30 },
  { id: 76, name: "Lessiver moquettes/tapis", frequency: "annuelle", zone: "Toutes", estimatedTime: 60 },
  { id: 77, name: "Nettoyer murs", frequency: "annuelle", zone: "Toutes", estimatedTime: 90 },
  { id: 78, name: "Nettoyer portes", frequency: "annuelle", zone: "Toutes", estimatedTime: 45 },
  { id: 79, name: "Laver toutes vitres", frequency: "annuelle", zone: "Toutes", estimatedTime: 60 },
  { id: 80, name: "Nettoyer grilles aération", frequency: "annuelle", zone: "Toutes", estimatedTime: 30 },
  { id: 81, name: "Laver couette/oreillers", frequency: "annuelle", zone: "Chambres", estimatedTime: 30 },
  { id: 82, name: "Taper/retourner matelas", frequency: "annuelle", zone: "Chambres", estimatedTime: 15 },
  { id: 83, name: "Vérifier alarmes incendie", frequency: "annuelle", zone: "Cuisine", estimatedTime: 10 },
  { id: 84, name: "Inspecter tuyaux fuites", frequency: "annuelle", zone: "Cuisine", estimatedTime: 20 },
  { id: 85, name: "Refaire joints silicone", frequency: "annuelle", zone: "Cuisine/SDB", estimatedTime: 60 },
  { id: 86, name: "Huiler plans bois", frequency: "annuelle", zone: "Cuisine", estimatedTime: 25 },
  { id: 87, name: "Réparer poignées cassées", frequency: "annuelle", zone: "Meubles", estimatedTime: 30 },
  { id: 88, name: "Tri livres/DVD/magazines", frequency: "annuelle", zone: "Salon", estimatedTime: 45 },
  { id: 89, name: "Réparer trous murs", frequency: "annuelle", zone: "Murs", estimatedTime: 40 },
  { id: 90, name: "Repeindre murs", frequency: "annuelle", zone: "Murs", estimatedTime: 240 },
  { id: 91, name: "Nettoyer gouttières", frequency: "annuelle", zone: "Extérieur", estimatedTime: 60 },
  { id: 92, name: "Laver pavés perron", frequency: "annuelle", zone: "Extérieur", estimatedTime: 45 },
  { id: 93, name: "Nettoyer barbecue", frequency: "annuelle", zone: "Extérieur", estimatedTime: 30 },
  { id: 94, name: "Trier outils jardin", frequency: "annuelle", zone: "Extérieur", estimatedTime: 35 },
  { id: 95, name: "Vérifier fondations", frequency: "annuelle", zone: "Extérieur", estimatedTime: 30 },
  { id: 96, name: "Nettoyer poignées/interrupteurs", frequency: "mensuelle", zone: "Toutes", estimatedTime: 15 },
  { id: 97, name: "Laver serviettes bain", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 98, name: "Tri frigo périmés", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 10 },
  { id: 99, name: "Nettoyer lave-linge", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 20 },
  { id: 100, name: "Faire carreaux", frequency: "trimestrielle", zone: "Sols", estimatedTime: 30 },

  // ===== 101-150 : BUREAU, ENTRÉE, CUISINE, SALON, SDB =====
  { id: 101, name: "Nettoyer clavier/souris ordinateur", frequency: "hebdomadaire", zone: "Bureau", estimatedTime: 10 },
  { id: 102, name: "Dépoussiérer imprimante/scanner", frequency: "hebdomadaire", zone: "Bureau", estimatedTime: 8 },
  { id: 103, name: "Ranger câbles/chargeurs", frequency: "hebdomadaire", zone: "Bureau", estimatedTime: 10 },
  { id: 104, name: "Essuyer tableau blanc/ardoise", frequency: "hebdomadaire", zone: "Bureau", estimatedTime: 5 },
  { id: 105, name: "Nettoyer étagères livres/papiers", frequency: "mensuelle", zone: "Bureau", estimatedTime: 25 },
  { id: 106, name: "Aspirer sous bureau/meubles", frequency: "mensuelle", zone: "Bureau", estimatedTime: 15 },
  { id: 107, name: "Trier documents archivés", frequency: "mensuelle", zone: "Bureau", estimatedTime: 40 },
  { id: 108, name: "Nettoyer téléphone fixe/portable", frequency: "mensuelle", zone: "Bureau", estimatedTime: 8 },
  { id: 109, name: "Laver tapis de bureau", frequency: "saisonnière", zone: "Bureau", estimatedTime: 20 },
  { id: 110, name: "Désinfecter chaise de bureau", frequency: "saisonnière", zone: "Bureau", estimatedTime: 15 },
  { id: 111, name: "Ranger entrée (chaussures)", frequency: "quotidienne", zone: "Entrée", estimatedTime: 5 },
  { id: 112, name: "Essuyer porte d'entrée", frequency: "quotidienne", zone: "Entrée", estimatedTime: 3 },
  { id: 113, name: "Balayer sol entrée", frequency: "quotidienne", zone: "Entrée", estimatedTime: 5 },
  { id: 114, name: "Nettoyer porte-manteau", frequency: "hebdomadaire", zone: "Entrée", estimatedTime: 10 },
  { id: 115, name: "Laver tapis de sol", frequency: "hebdomadaire", zone: "Entrée", estimatedTime: 15 },
  { id: 116, name: "Dépoussiérer appliques murales", frequency: "mensuelle", zone: "Entrée", estimatedTime: 10 },
  { id: 117, name: "Nettoyer miroir d'entrée", frequency: "mensuelle", zone: "Entrée", estimatedTime: 5 },
  { id: 118, name: "Trier sacs/écharpes", frequency: "mensuelle", zone: "Entrée", estimatedTime: 15 },
  { id: 119, name: "Lessiver murs entrée", frequency: "saisonnière", zone: "Entrée", estimatedTime: 30 },
  { id: 120, name: "Nettoyer serrure/porte", frequency: "annuelle", zone: "Entrée", estimatedTime: 15 },
  { id: 121, name: "Nettoyer hotte aspirante filtres", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 20 },
  { id: 122, name: "Dégraisser plaque induction", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 10 },
  { id: 123, name: "Nettoyer tiroirs ustensiles", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 25 },
  { id: 124, name: "Laver planches à découper", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 8 },
  { id: 125, name: "Désinfecter éponge/torchon", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 3 },
  { id: 126, name: "Nettoyer congélateur", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 45 },
  { id: 127, name: "Vider placard provisions", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 20 },
  { id: 128, name: "Polir robinet évier", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 8 },
  { id: 129, name: "Nettoyer joints frigo", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 15 },
  { id: 130, name: "Laver gants four", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 10 },
  { id: 131, name: "Aspirer dessous canapé", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 12 },
  { id: 132, name: "Nettoyer télécommandes", frequency: "quotidienne", zone: "Salon", estimatedTime: 3 },
  { id: 133, name: "Laver housses coussins", frequency: "mensuelle", zone: "Salon", estimatedTime: 20 },
  { id: 134, name: "Dépoussiérer bibliothèque", frequency: "mensuelle", zone: "Salon", estimatedTime: 20 },
  { id: 135, name: "Nettoyer vitres tableaux", frequency: "mensuelle", zone: "Salon", estimatedTime: 15 },
  { id: 136, name: "Aspirer plinthes sol", frequency: "mensuelle", zone: "Salon", estimatedTime: 15 },
  { id: 137, name: "Laver rideaux salon", frequency: "saisonnière", zone: "Salon", estimatedTime: 30 },
  { id: 138, name: "Nettoyer dessous meubles TV", frequency: "saisonnière", zone: "Salon", estimatedTime: 20 },
  { id: 139, name: "Polir table basse", frequency: "mensuelle", zone: "Salon", estimatedTime: 10 },
  { id: 140, name: "Nettoyer ventilateurs plafond", frequency: "saisonnière", zone: "Salon", estimatedTime: 20 },
  { id: 141, name: "Nettoyer baignoire/Jacuzzi", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 15 },
  { id: 142, name: "Laver rideau douche", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 15 },
  { id: 143, name: "Nettoyer joints carrelage", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 30 },
  { id: 144, name: "Désinfecter brosse WC", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 5 },
  { id: 145, name: "Vider tiroirs salle bain", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 20 },
  { id: 146, name: "Nettoyer miroir anti-buée", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 8 },
  { id: 147, name: "Laver tapis antidérapant", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 148, name: "Détartrer pommeau douche", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 15 },
  { id: 149, name: "Nettoyer sèche-cheveux", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 8 },
  { id: 150, name: "Inspecter moisissures", frequency: "saisonnière", zone: "Salle de bain", estimatedTime: 15 },

  // ===== 151-200 : CHAMBRES, BUANDERIE, COMMUN, EXTÉRIEUR, FENÊTRES =====
  { id: 151, name: "Changer housse oreiller", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 10 },
  { id: 152, name: "Aspirer tête lit", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 8 },
  { id: 153, name: "Nettoyer armoire intérieure", frequency: "mensuelle", zone: "Chambres", estimatedTime: 30 },
  { id: 154, name: "Laver rideaux chambre", frequency: "saisonnière", zone: "Chambres", estimatedTime: 25 },
  { id: 155, name: "Nettoyer dessous commode", frequency: "mensuelle", zone: "Chambres", estimatedTime: 15 },
  { id: 156, name: "Trier lingerie", frequency: "mensuelle", zone: "Chambres", estimatedTime: 25 },
  { id: 157, name: "Désodoriser poubelle chambre", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 5 },
  { id: 158, name: "Nettoyer abat-jours", frequency: "mensuelle", zone: "Chambres", estimatedTime: 12 },
  { id: 159, name: "Aspirer sommier", frequency: "saisonnière", zone: "Chambres", estimatedTime: 15 },
  { id: 160, name: "Nettoyer porte placard coulissante", frequency: "saisonnière", zone: "Chambres", estimatedTime: 20 },
  { id: 161, name: "Nettoyer lave-linge joints", frequency: "mensuelle", zone: "Buanderie", estimatedTime: 15 },
  { id: 162, name: "Vider filtre sèche-linge", frequency: "hebdomadaire", zone: "Buanderie", estimatedTime: 5 },
  { id: 163, name: "Nettoyer panier linge sale", frequency: "hebdomadaire", zone: "Buanderie", estimatedTime: 8 },
  { id: 164, name: "Laver étagères produits", frequency: "mensuelle", zone: "Buanderie", estimatedTime: 15 },
  { id: 165, name: "Nettoyer sol buanderie", frequency: "hebdomadaire", zone: "Buanderie", estimatedTime: 10 },
  { id: 166, name: "Trier détergents périmés", frequency: "saisonnière", zone: "Buanderie", estimatedTime: 20 },
  { id: 167, name: "Nettoyer fer à repasser", frequency: "mensuelle", zone: "Buanderie", estimatedTime: 10 },
  { id: 168, name: "Ranger planche repassage", frequency: "hebdomadaire", zone: "Buanderie", estimatedTime: 3 },
  { id: 169, name: "Nettoyer aspirateur", frequency: "mensuelle", zone: "Commun", estimatedTime: 15 },
  { id: 170, name: "Vider sac/bac aspirateur", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 5 },
  { id: 171, name: "Nettoyer balai serpillière", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 8 },
  { id: 172, name: "Laver chiffons microfibres", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 10 },
  { id: 173, name: "Ranger matériel nettoyage", frequency: "mensuelle", zone: "Commun", estimatedTime: 15 },
  { id: 174, name: "Nettoyer seaux/éponges", frequency: "mensuelle", zone: "Commun", estimatedTime: 10 },
  { id: 175, name: "Désinfecter vadrouille", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 8 },
  { id: 176, name: "Laver balais", frequency: "saisonnière", zone: "Commun", estimatedTime: 15 },
  { id: 177, name: "Nettoyer gouttières", frequency: "annuelle", zone: "Extérieur", estimatedTime: 60 },
  { id: 178, name: "Laver terrasse pavés", frequency: "saisonnière", zone: "Extérieur", estimatedTime: 45 },
  { id: 179, name: "Nettoyer meubles jardin", frequency: "annuelle", zone: "Extérieur", estimatedTime: 40 },
  { id: 180, name: "Vider nid oiseaux/gouttières", frequency: "annuelle", zone: "Extérieur", estimatedTime: 30 },
  { id: 181, name: "Laver volets extérieurs", frequency: "annuelle", zone: "Extérieur", estimatedTime: 50 },
  { id: 182, name: "Nettoyer barbecue/grill", frequency: "annuelle", zone: "Extérieur", estimatedTime: 35 },
  { id: 183, name: "Tondre/trier jardin", frequency: "saisonnière", zone: "Extérieur", estimatedTime: 60 },
  { id: 184, name: "Nettoyer garage sol", frequency: "saisonnière", zone: "Garage", estimatedTime: 30 },
  { id: 185, name: "Ranger outils garage", frequency: "mensuelle", zone: "Garage", estimatedTime: 25 },
  { id: 186, name: "Nettoyer voiture intérieure", frequency: "mensuelle", zone: "Garage", estimatedTime: 35 },
  { id: 187, name: "Balayer sol garage", frequency: "hebdomadaire", zone: "Garage", estimatedTime: 10 },
  { id: 188, name: "Nettoyer étagères garage", frequency: "saisonnière", zone: "Garage", estimatedTime: 30 },
  { id: 189, name: "Vérifier détecteurs fumée", frequency: "annuelle", zone: "Commun", estimatedTime: 15 },
  { id: 190, name: "Nettoyer grilles ventilation", frequency: "annuelle", zone: "Commun", estimatedTime: 30 },
  { id: 191, name: "Laver stores intérieurs", frequency: "saisonnière", zone: "Fenêtres", estimatedTime: 35 },
  { id: 192, name: "Nettoyer moustiquaires", frequency: "saisonnière", zone: "Fenêtres", estimatedTime: 25 },
  { id: 193, name: "Polir vitres intérieure", frequency: "mensuelle", zone: "Fenêtres", estimatedTime: 20 },
  { id: 194, name: "Nettoyer cadres fenêtres", frequency: "saisonnière", zone: "Fenêtres", estimatedTime: 20 },
  { id: 195, name: "Trier magazines/papiers", frequency: "mensuelle", zone: "Commun", estimatedTime: 20 },
  { id: 196, name: "Nettoyer interrupteurs/poignées", frequency: "hebdomadaire", zone: "Toutes", estimatedTime: 12 },
  { id: 197, name: "Désinfecter téléphone/tablette", frequency: "quotidienne", zone: "Commun", estimatedTime: 3 },
  { id: 198, name: "Laver corbeilles poubelles", frequency: "hebdomadaire", zone: "Toutes", estimatedTime: 15 },
  { id: 199, name: "Nettoyer prises électriques", frequency: "mensuelle", zone: "Toutes", estimatedTime: 15 },
  { id: 200, name: "Vérifier joints fenêtres fuites", frequency: "annuelle", zone: "Toutes", estimatedTime: 30 },

  // ===== 201-250 : TÂCHES COMPLÉMENTAIRES =====
  { id: 201, name: "Nettoyer bols/ustensiles animaux", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 10 },
  { id: 202, name: "Assainir siphon évier", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 15 },
  { id: 203, name: "Nettoyer WC en profondeur (réservoir)", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 15 },
  { id: 204, name: "Dépoussiérer interrupteurs/poignées", frequency: "hebdomadaire", zone: "Toutes", estimatedTime: 10 },
  { id: 205, name: "Laver tapis entrée/antidérapants", frequency: "mensuelle", zone: "Entrée/SDB", estimatedTime: 20 },
  { id: 206, name: "Nettoyer rideaux/tulle", frequency: "saisonnière", zone: "Toutes", estimatedTime: 40 },
  { id: 207, name: "Dépoussiérer lampes/ampoules", frequency: "mensuelle", zone: "Toutes", estimatedTime: 15 },
  { id: 208, name: "Récurer poubelles int/ext", frequency: "hebdomadaire", zone: "Toutes", estimatedTime: 12 },
  { id: 209, name: "Entretien meubles cuisine (joints)", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 20 },
  { id: 210, name: "Nettoyer calorifères/radiateurs", frequency: "mensuelle", zone: "Toutes", estimatedTime: 25 },
  { id: 211, name: "Laver ventilateurs/clim", frequency: "saisonnière", zone: "Toutes", estimatedTime: 30 },
  { id: 212, name: "Nettoyer plaques éclairage", frequency: "mensuelle", zone: "Toutes", estimatedTime: 15 },
  { id: 213, name: "Dépoussiérer plafond/murs hauts", frequency: "saisonnière", zone: "Toutes", estimatedTime: 35 },
  { id: 214, name: "Laver portes/chambranles", frequency: "saisonnière", zone: "Toutes", estimatedTime: 40 },
  { id: 215, name: "Nettoyer plinthes encastrées", frequency: "mensuelle", zone: "Toutes", estimatedTime: 20 },
  { id: 216, name: "Éliminer toiles d'araignées", frequency: "mensuelle", zone: "Toutes", estimatedTime: 12 },
  { id: 217, name: "Nettoyer dessous/arrière meubles", frequency: "saisonnière", zone: "Toutes", estimatedTime: 45 },
  { id: 218, name: "Laver canalisations aération", frequency: "annuelle", zone: "Toutes", estimatedTime: 40 },
  { id: 219, name: "Dégivrer congélateur", frequency: "annuelle", zone: "Cuisine", estimatedTime: 60 },
  { id: 220, name: "Nettoyer sèche-linge intérieur", frequency: "annuelle", zone: "Buanderie", estimatedTime: 30 },
  { id: 221, name: "Laver fenêtres extérieures", frequency: "annuelle", zone: "Toutes", estimatedTime: 60 },
  { id: 222, name: "Nettoyer volets roulants", frequency: "annuelle", zone: "Fenêtres", estimatedTime: 40 },
  { id: 223, name: "Balayer terrasse/porche", frequency: "saisonnière", zone: "Extérieur", estimatedTime: 20 },
  { id: 224, name: "Laver revêtement extérieur", frequency: "annuelle", zone: "Extérieur", estimatedTime: 90 },
  { id: 225, name: "Nettoyer meubles/coussins jardin", frequency: "annuelle", zone: "Extérieur", estimatedTime: 35 },
  { id: 226, name: "Vider tiroirs cuisine (ustensiles)", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 25 },
  { id: 227, name: "Nettoyer cadres fenêtres", frequency: "mensuelle", zone: "Fenêtres", estimatedTime: 15 },
  { id: 228, name: "Décrasser joints carrelage", frequency: "mensuelle", zone: "Cuisine/SDB", estimatedTime: 30 },
  { id: 229, name: "Nettoyer lave-vaisselle joints", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 15 },
  { id: 230, name: "Vider frigo/congélateur complet", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 40 },
  { id: 231, name: "Ranger escaliers/aspirer marches", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 15 },
  { id: 232, name: "Nettoyer tableau électrique", frequency: "annuelle", zone: "Commun", estimatedTime: 25 },
  { id: 233, name: "Laver stores vénitiens", frequency: "saisonnière", zone: "Fenêtres", estimatedTime: 30 },
  { id: 234, name: "Nettoyer moustiquaires", frequency: "saisonnière", zone: "Fenêtres", estimatedTime: 25 },
  { id: 235, name: "Désinfecter éponges/coupelles", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 3 },
  { id: 236, name: "Nettoyer micro-ondes plateau", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 8 },
  { id: 237, name: "Secouer/aérer oreillers", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 10 },
  { id: 238, name: "Faire lessives/repassage", frequency: "hebdomadaire", zone: "Buanderie", estimatedTime: 60 },
  { id: 239, name: "Arroser plantes/nettoyer pots", frequency: "hebdomadaire", zone: "Toutes", estimatedTime: 15 },
  { id: 240, name: "Nettoyer machine café (réservoir)", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 15 },
  { id: 241, name: "Vérifier joints silicone fissures", frequency: "annuelle", zone: "Salle de bain/Cuisine", estimatedTime: 30 },
  { id: 242, name: "Nettoyer aspirateur serpentins", frequency: "mensuelle", zone: "Commun", estimatedTime: 15 },
  { id: 243, name: "Laver serpillière/vadrouille", frequency: "hebdomadaire", zone: "Commun", estimatedTime: 8 },
  { id: 244, name: "Trier produits ménagers périmés", frequency: "saisonnière", zone: "Buanderie", estimatedTime: 20 },
  { id: 245, name: "Nettoyer fer repassage semelle", frequency: "mensuelle", zone: "Buanderie", estimatedTime: 10 },
  { id: 246, name: "Balayer allée extérieure", frequency: "saisonnière", zone: "Extérieur", estimatedTime: 25 },
  { id: 247, name: "Nettoyer pare-baignoire", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 12 },
  { id: 248, name: "Dépoussiérer moulures/plafonds", frequency: "saisonnière", zone: "Toutes", estimatedTime: 35 },
  { id: 249, name: "Nettoyer tapis à sec", frequency: "annuelle", zone: "Toutes", estimatedTime: 50 },
  { id: 250, name: "Vérifier alarmes CO/monoxyde", frequency: "annuelle", zone: "Commun", estimatedTime: 15 },
];

export const ZONES = [...new Set(TASKS.map(t => t.zone))];
